# -*- coding: utf-8 -*-
"""TASK_5_prob_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

class characters:
    def isValid(self, s: str) -> bool:
        stack = []
        if len(s)<2:
            return False
        for ch in s:
            if ch == "(" or ch == "{" or ch == "[":
                stack.append(ch)
            elif ch == ")":
                if not stack or stack.pop() != "(":
                    return False
                
            elif ch == "]":
                if not stack or stack.pop() != "[":
                    return False
                
            elif ch == "}":
                if not stack == True or stack.pop() != "{":
                    return False
                
        
        return True
s=input()
string=characters()
string.isValid(s)

class characters:
    def isValid(self, s: str) -> bool:
        stack = []
        if len(s)<2:
            return False
        for ch in s:
            if ch == "(" or ch == "{" or ch == "[":
                stack.append(ch)
            elif ch == ")":
                if not stack or stack.pop() != "(":
                    return False
                
            elif ch == "]":
                if not stack or stack.pop() != "[":
                    return False
                
            elif ch == "}":
                if not stack == True or stack.pop() != "{":
                    return False
                
        
        return True
s=input()
string=characters()
string.isValid(s)