# -*- coding: utf-8 -*-
"""TASK_4_prob_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

n,k=map(int,input().split( ))
x=[int(x) for x in input().split( )]
def most_frequent(x):
  frequent=x[0]
  num=[]
  most=[]
  for i in x:
    cur_freq=x.count(i)
    if (cur_freq>= k):
      num.append(i)
  res = [*set(num)]
  return res
print(most_frequent(x))