# -*- coding: utf-8 -*-
"""TASK_4_prob_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

n=int(input())
list=[]
for i in range(n):
  word=input()
  list.append(word)
  i=0
print(" ")
while i<n:
  j=0
  while j<i+1 :
    print(list[n-1] ,end=" ")
    n-=1
    j+=1
  print("\r")
  i+=1