# -*- coding: utf-8 -*-
"""task_4_prob_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYqTDEYLcqHYyJ8a7-_4pveloMdu8TJq
"""

n = int(input("Enter the number of rows and columns:"))
matrix = []
for i in range(n):		
	arr =[]
	for j in range(n):	 
		arr.append(int(input()))
	matrix.append(arr)
def rotate90Clockwise(matrix):
	N = len(matrix[0])
	for i in range(N // 2):
		for j in range(i, N - i - 1):
			temp = matrix[i][j]
			matrix[i][j] = matrix[N - 1 - j][i]
			matrix[N - 1 - j][i] = matrix[N - 1 - i][N - 1 - j]
			matrix[N - 1 - i][N - 1 - j] = matrix[j][N - 1 - i]
			matrix[j][N - 1 - i] = temp
def printMatrix(matrix):
	N = len(matrix[0])
	for i in range(N):
		print(matrix[i])
rotate90Clockwise(matrix)
printMatrix(matrix)