# -*- coding: utf-8 -*-
"""prob_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

num=int(input())
num_1=num
reversed_num=0
while num != 0 :
  digit = num % 10
  reversed_num = reversed_num*10 + digit
  num //= 10
if num_1 == reversed_num :
  print(True)
else :
  print(False)
print(str(reversed_num))

num=int(input())
num_1=num
reversed_num=0
while num != 0 :
  digit = num % 10
  reversed_num = reversed_num*10 + digit
  num //= 10
if num_1 == reversed_num :
  print(True)
else :
  print(False)
print(str(reversed_num))

