# -*- coding: utf-8 -*-
"""prob_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZVZAfHtyfub_LE34eVhrP-BxeO_XJxE
"""

n=int(input())
sum=0
for i in range (n+1):
  if(i%3==0 or i%5==0):
    sum+=i
print(sum)