# -*- coding: utf-8 -*-
"""prob_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LxsOq4H__YibZy3qT50cxJzg1HOP6iNk
"""

#2
n=int(input())
def factorial(n):
  if n==2 :
    return 2
  else:
    return n*factorial(n-1)
factorial(n)



