# -*- coding: utf-8 -*-
"""prob_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RhJN9V-ImCtwT_UlRPAUPCpuM8LwXc2t
"""

#4
n=int(input())
sum=0
for i in range (0,n+1):
  sum+=i
print(sum)





