# -*- coding: utf-8 -*-
"""prob_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5iFscyLWZ6gyTAK7fdccKbruBGX4LGl
"""

n=int(input())
m=int(input())
area=n*m
print(area)
primeter=(n+m)*2
print(primeter)