# -*- coding: utf-8 -*-
"""TASK_6_prob5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

import sys
n=[]
k = int(input().strip())
for a0 in range(k):
    s = input().strip()
    n.append(s)
    a="hackerrank"
def hakerrankstring(n):
  for j in range(len(n)):
     c=0
     for i in n[j]:
       if i==a[c]:
         c+=1
       if c>=10:
         break
     if c==10:
        print("YES")
     else:
        print("NO")
hakerrankstring(n)