# -*- coding: utf-8 -*-
"""TASK_6_prob6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

def circularArrayRotation(a, k, queries):
    # Write your code here
    n=len(a)
    
    ans=[]
    for q in queries:
        ans.append(a[(n-k+q)%n])
        
    for i in range(len(ans)):
      print(ans[i])
#if __name__ == '__main__':
  #  fptr = open(os.environ['OUTPUT_PATH'], 'w')

first_multiple_input = input().rstrip().split()
n = int(first_multiple_input[0])
k = int(first_multiple_input[1])
q = int(first_multiple_input[2])
a = list(map(int, input().rstrip().split()))
queries = []
for _ in range(q):
        queries_item = int(input().strip())
        queries.append(queries_item)

result = circularArrayRotation(a, k, queries)

   # fptr.write('\n'.join(map(str, result)))
   # fptr.write('\n')

   # fptr.close()