# -*- coding: utf-8 -*-
"""TASK_6_prob3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

def climbingLeaderboard(ranked, player):
    ranked = sorted(list(set(ranked)), reverse=True)
    player = sorted(player, reverse=True)
    l=len(ranked)
    j=0
    ans=[]
    for i in range(len(player)):
        while j<l and player[i]<ranked[j]:
            j+=1
        ans.append(j+1)
    for i in range(len(ans)-1, -1,-1):
     print(ans[i])  
#if __name__ == '__main__':
   # fptr = open(os.environ['OUTPUT_PATH'], 'w')
#ranked_count = int(input().strip())
ranked = list(map(int, input().rstrip().split()))
#player_count = int(input().strip())
player = list(map(int, input().rstrip().split()))
result = climbingLeaderboard(ranked, player)
   # fptr.write('\n'.join(map(str, result)))