# -*- coding: utf-8 -*-
"""TASK_7_prob_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Z2Chw2xFTinUw1t-4D80F97ZdaRurv8
"""

ch_1=str(input())
l=len(ch_1)
ch_2=[]
i=0
while i <(l):
  if ch_1[i] =='.' :
    ch_2.append('0')
  elif ch_1[i] =='-' and ch_1[i] =='.':
       ch_2.append('1')
  elif ch_1[i] =='-' and ch_1[i] =='-':
      ch_2.append('2')
      i+=1
  i+=1
print(''.join(ch_2))