# -*- coding: utf-8 -*-
"""TASK_7_prob_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Z2Chw2xFTinUw1t-4D80F97ZdaRurv8
"""

class Solution:
    def kClosest(self, points: List[List[int]], k: int) -> List[List[int]]:
        minHeap = []
        for x, y in points:
           minHeap += [[x**2 + y**2, x, y]]

        heapq.heapify(minHeap)

        res = []
        for i in range(k):
            d, x, y = heapq.heappop(minHeap)
            res.append([x, y])

        return res