# -*- coding: utf-8 -*-
"""TASK_7_prob_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Z2Chw2xFTinUw1t-4D80F97ZdaRurv8
"""

import math
import os
import random
import re
import sys
def chocolateFeast(n, c, m):
    # Write your code here
    count = 0;
    value = math.floor(n / c);
    while (True) :
        focus = value + (count % m);

        count += value;

        if (focus < m) :
            break;

        value = math.floor(focus / m);
    return count;
#if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')
t = int(input().strip())
for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        c = int(first_multiple_input[1])

        m = int(first_multiple_input[2])

        result = chocolateFeast(n, c, m)
        print(result)

        #fptr.write(str(result) + '\n')

    #fptr.close()