# -*- coding: utf-8 -*-
"""TASK_7_prob_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Z2Chw2xFTinUw1t-4D80F97ZdaRurv8
"""

import math
import os
import random
import re
import sys

def main(N):
    sum0 = 0
    D = N[0][0]-N[1][0]
    M = N[0][1]-N[1][1]
    Y = N[0][2]-N[1][2]

    if D > 0 and M == 0 and Y == 0:
        sum0 = 15*(D)
    elif M > 0 and Y == 0:
        sum0 = 500*(M)
    elif Y > 0:
        sum0 = 10000*(Y)

    print(sum0)
# Complete the 'libraryFine' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER d1
#  2. INTEGER m1
#  3. INTEGER y1
#  4. INTEGER d2
#  5. INTEGER m2
#  6. INTEGER y2
#

def libraryFine(d1, m1, y1, d2, m2, y2):
    sum0 = 0
    D = d1-d2
    M = m1-m2
    Y = y1-y2
    if D > 0 and M == 0 and Y == 0:
        sum0 = 15*(D)
    elif M > 0 and Y == 0:
        sum0 = 500*(M)
    elif Y > 0:
        sum0 = 10000*(Y)

    print(sum0)
    # Write your code here

#if __name__ == '__main__':
  #  fptr = open(os.environ['OUTPUT_PATH'], 'w')
first_multiple_input = input().rstrip().split()

d1 = int(first_multiple_input[0])

m1 = int(first_multiple_input[1])

y1 = int(first_multiple_input[2])

second_multiple_input = input().rstrip().split()

d2 = int(second_multiple_input[0])

m2 = int(second_multiple_input[1])

y2 = int(second_multiple_input[2])

result = libraryFine(d1, m1, y1, d2, m2, y2)

    #fptr.write(str(result) + '\n')

    #fptr.close()