# -*- coding: utf-8 -*-
"""prob_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1oVey7w84rxuoQz9mveWaRrdJXANDhV
"""

def insertionSort(arr):
  for i in range(1, len(arr)):
      key = arr[i]
      j = i-1
      while j >=0 and key < arr[j] :
          arr[j+1] = arr[j]
          j -= 1
          arr[j+1] = key
arr = [12, 11, 13, 5, 6]
insertionSort(arr)
print(arr)
print("the time that it takes is n^2")
print ("it works that takes the second element and compare it to all elements then add 1 and repeat the processing again ")