# -*- coding: utf-8 -*-
"""prob_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

import random

def generate_number():
  x=random.randint(100,999)
  print("enter a 3-digit number:" ,x )
  digit_1 = x%10
  digit_2 = int((x/10 )%10)
  digit_3 = int((x/100))
  print(digit_1)
  print(digit_2)
  print(digit_3)
  list_guess=[]
  for j in range(0,3):
    y=int(input("enter the digits :"))
    list_guess.append(y)
  print(list_guess)
  hit=0
  miss=0
  for i in range(0,3):
    if digit_1 == list_guess[i] or digit_2 == list_guess[i] or digit_3 == list_guess[i] :
      hit+=1
    else :
      miss+=1
  print(hit ,"hits" " , ", miss ,"miss")
generate_number()



