# -*- coding: utf-8 -*-
"""prob_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_n_07GSFAP3A7pBi06ppxGVBZAohs15X
"""

def remove_duplicated(arr):
  res = []
  for x in arr :
    if x not in res :
      res.append(x)
  print ("The list after removing duplicates : ", res)
n = int(input("the length of array :"))
arr=[]
for i in range(n):
  x=int(input())
  arr.append(x)
remove_duplicated(arr)