# -*- coding: utf-8 -*-
"""prob_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alfsf0AfPVDl2ZnY-Tmk0s9g1DcuAi2z
"""

def is_subsquence(s1 , s2):
  n=len(s1)
  m=len(s2)
  i=0
  j=0
  while(i<n and j<m):
    if (s1[i] == s2[j]) :
      i+=1
    j+=1
    return i==n

s1="hello"
s2=str(input())
if (is_subsquence(s1 , s2)):
  print ("Yes")
else:
  print("No")