# -*- coding: utf-8 -*-
"""TASK_3_prob_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

import numpy as np 
n=int(input())
arr=[]
R = n
p=0
s=0

print("Enter the entries in a single line (separated by space): ")
for i in range(R*R):
  k=int(input())
  arr.append(k)
arr=np.array(arr)
arr=arr.reshape(3,3)
print(arr) 
for i in range(R):
   p=p+arr[i][i]  
   s=s+arr[i][n-i-1] 
      
differance=abs(p-s)
print("differance between its diagonals is :",differance)