# -*- coding: utf-8 -*-
"""TASK_3_prob_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7ZCiffontEDXa1oQxALVxDy9UiZztmV
"""

def solve(students):
   min_mark = min(x[1] for x in students)
   students = [x for x in students if x[1] > min_mark]
   min2_mark = min(x[1] for x in students)
   students = sorted([x[0] for x in students if x[1] == min2_mark])
   for x in students:
      print(x)

N=int(input())
nlist_comp1=[]
nest=[]
for i in range(N):
  for j in range(2):
    n=input()
    nest.append(n)
  nlist_comp1[i].append(nest[j])
print(nlist_comp1)

